### ISSUE TITLE
Create cache for project names

### ISSUE THREAD

**Issue by Gerrit91** [fi-ts/gardener-extension-accounting#1]
At the moment every reconciliation does a proejct find only to resolve the project name. It would be great to have a cache call for all projects at once and then just refresh entries after 30 minutes because project names can actually not change.

Maybe consider adding a "lazy map cache" (don't know if this is a good name) in the metal-lib for this: https://github.com/metal-stack/metal-lib/tree/master/pkg/cache

**Comment by vknabel** [comment]
@Gerrit91 can we close this? #4 has already been merged

**Comment by Gerrit91** [comment]
Done.
